/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_VolumeControl */

#ifndef _Included_jni_VolumeControl
#define _Included_jni_VolumeControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_VolumeControl
 * Method:    changeVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_utils_jni_VolumeControl_changeVolume
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
